require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Sample' do
  rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', :path => rn_maps_path 
  pod 'GoogleMaps' 
  pod 'Google-Maps-iOS-Utils'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'SampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  
  # 직접 추가한 내용
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # 원래 있던 설정 // 삭제 금지
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end

  # use_flipper!({ 'Flipper-Folly' => '2.5' })
  # post_install do |installer|
  # flipper_post_install(installer)
  # end

end